### ISSUE TITLE
是否支持服务端渲染

### ISSUE THREAD

**Issue by jinchaoxiang** [airyland/vux#1217]
### Version
2.1.1-r14
### Android or iOS

> For Android issues, please specify the brand, model and browser

### Your Codes 
是否支持服务端渲染 我试着做了下报如下错误
``` html
<!--put your code here-->
```
ReferenceError: window is not defined
    at detectWebp (~/webp-support/index.js:3:0)
    at Object.<anonymous> (~/webp-support/index.js:23:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2b915e9ce41df6c4fe28:19:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:30246:71)
    at __webpack_require__ (webpack:/webpack/bootstrap 2b915e9ce41df6c4fe28:19:0)
    at Object.module.exports.module.exports (~/vux/src/components/x-img/index.vue?fa1a:7:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2b915e9ce41df6c4fe28:19:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:31460:93)
    at __webpack_require__ (webpack:/webpack/bootstrap 2b915e9ce41df6c4fe28:19:0)
    at Object.<anonymous> (src/components/main/obligatory.vue?36c7:7:0)

**Comment by jinchaoxiang** [comment]
用的是vue+vuex+vue-router+vux 只是import了vux里的几个组件 打包出来的js+css竟然要1m（不包含vendor） vux-loader里的vux-ui也配了 感觉并没有按需加载 看了1m里面的代码还包含一大堆城市列表信息 和wxjssdk 可我都没用这些组件啊

**Comment by airyland** [comment]
不支持。不在当前主要开发目标。
打包过大必定是配置不对，直接使用 vux2 模板试试。

**Comment by jinchaoxiang** [comment]
希望以后能支持服务端渲染 毕竟是趋势

**Comment by airyland** [comment]
个人意见是服务端渲染主要是用以 SEO，但是对于移动端来说似乎没有必要？
