### ISSUE TITLE
npm run test 出现错误的问题

### ISSUE THREAD

**Issue by AZmake** [airyland/vux#1236]
0、使用`vue init airyland/vux2 projectPath`，创建项目

1、/src/router/index.js里面

```javascript
import Vue from 'vue'
import Router from 'vue-router'
import Hello from '@/components/Hello'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: Hello
    }
  ]
})
```

`import Hello from '@/components/Hello` 这个导致了 `npm run dev`的时候的页面是`HelloFromVux.vue`，而`test` 里面的`e2etest`的模板`/specs/test.js`,却是根据`Hello.vue`来写测试用例的，这导致了 `npm run test` 出现错误

```shell
Running:  default e2e tests
 ✔ Element <#app> was visible after 88 milliseconds.
 ✖ Testing if element <.hello> is present.  - expected "present" but got: "not present"
    at Object.defaultE2eTests [as default e2e tests] (/Users/azmake/Desktop/zhwWebApp/test/e2e/specs/test.js:14:15)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)


FAILED:  1 assertions failed and 1 passed (2.33s)

 _________________________________________________

 TEST FAILURE:  1 assertions failed, 1 passed. (2.482s)

 ✖ test

   - default e2e tests (2.33s)
   Testing if element <.hello> is present.  - expected "present" but got: "not present"
       at Object.defaultE2eTests [as default e2e tests] (/Users/azmake/Desktop/zhwWebApp/test/e2e/specs/test.js:14:15)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)


npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
npm ERR! app@1.0.0 e2e: `node test/e2e/runner.js`
...
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/.npm/_logs/2017-04-11T06_02_23_981Z-debug.log
```

而且根据Hello.vue页面测试的例子的`.assert.elementCount('img', 1)` img的count应该是0，而不是1

**Comment by AZmake** [comment]
是我错了，没有想到main.js里面还有路由，感情index.js只是个参考例子,

但是测试用例还是牛头不对马嘴啊
