### ISSUE TITLE
想要做ssr，使用了vue-hackernews-2.0的方法发现很多不支持

### ISSUE THREAD

**Issue by ljw1811** [airyland/vux#1259]
运行node server.js，发现第一个问题是src/plugins/title/index.js找不到，到node_modules中找到相关代码注掉解决问题。
![image](https://cloud.githubusercontent.com/assets/1333189/24999011/84f8e25a-206e-11e7-9e05-c288f4519540.png)

再次运行，访问首页报错
![2017-04-13 at 17](https://cloud.githubusercontent.com/assets/1333189/24999351/c351f766-206f-11e7-82a7-75f105ffb122.png)

查看vue-server-renderer源码和webpack.server.config.js
```
const webpack = require('webpack')
const merge = require('webpack-merge')
const base = require('./webpack.base.config')
const VueSSRPlugin = require('vue-ssr-webpack-plugin')

module.exports = merge(base, {
  target: 'node',
  devtool: '#source-map',
  entry: './src/entry-server.js',
  output: {
    filename: 'server-bundle.js',
    libraryTarget: 'commonjs2'
  },
  resolve: {
    alias: {
      'create-api': './create-api-server.js'
    }
  },
  externals: Object.keys(require('../package.json').dependencies), # 读取的是dependencies
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
      'process.env.VUE_ENV': '"server"'
    }),
    new VueSSRPlugin()
  ]
})

```
暂时把vux放到devDependencies中
![2017-04-13 at 17 46](https://cloud.githubusercontent.com/assets/1333189/24999891/dd8e5ae6-2071-11e7-9d9d-ff26cef6f29a.png)

再次运行，访问首页
```
server-bundle.js
evaluateModule   file::::
vue
evaluateModule   file::::
vuex
evaluateModule   file::::
axios
evaluateModule   file::::
path
error during render : /favicon.ico
ReferenceError: window is not defined
    at Object.<anonymous> (~/vux/src/components/popup/popup.js:2:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cd04134ce8cae84d30e9:19:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:18549:65)
    at __webpack_require__ (webpack:/webpack/bootstrap cd04134ce8cae84d30e9:19:0)
    at Object.<anonymous> (~/vux/src/components/popup/index.vue?6cad:7:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cd04134ce8cae84d30e9:19:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:16141:65)
    at __webpack_require__ (webpack:/webpack/bootstrap cd04134ce8cae84d30e9:19:0)
    at Object.<anonymous> (~/vux/src/components/calendar/index.vue?e845:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cd04134ce8cae84d30e9:19:0)

```

查看另一个ui框架的issue有[相关说明](https://github.com/ElemeFE/element/issues/333)，不过没有解决方法。

@airyland 有没有考虑ssr问题的支持？

**Comment by airyland** [comment]
Sorry，暂时还没空研究这个，ssr 支持不在短期目标内。

#785
