### ISSUE TITLE
根据官网教程安装完成之后报错

### ISSUE THREAD

**Issue by AliKhan1990** [airyland/vux#1390]
> vue2+elementUI 报错：
```
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1] has an unknown property 'plugins'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, compiler?, rules?, test?, use? }
    at webpack (/project/vue_starter/market/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/project/vue_starter/market/build/dev-server.js:59:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
```
该如何解决呀，感谢！🙏

**Comment by airyland** [comment]
你使用 elementUI 来 VUX 提啥 issue？！

**Comment by AliKhan1990** [comment]
不是，之前用的elementUI，两者会有冲突吗？
