### ISSUE TITLE
按官网步骤安装完成后报错

### ISSUE THREAD

**Issue by AliKhan1990** [airyland/vux#1391]
**用的是vue2，抛出错误：**

> 错误信息

```
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1] has an unknown property 'plugins'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, compiler?, rules?, test?, use? }
    at webpack (/project/vue_starter/market/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/project/vue_starter/market/build/dev-server.js:59:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
```
> webpack.base.conf.js配置文件
```
const path = require('path')
const utils = require('./utils')
const config = require('../config')
const fileloader = require("file-loader");
const vuxLoader = require('vux-loader')
const vueLoaderConfig = require('./vue-loader.conf')
const merge = require('webpack-merge')

function resolve(dir) {
  return path.join(__dirname, '..', dir)
}
const webpackConfig = module.exports = {// 原来的 module.exports 代码赋值给变量 webpackConfig
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
      'components': resolve('/src/components'),
      'common': resolve('/src/common')
    },
    enforceExtension:false
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig,
        plugins: [{
          name:'vux-ui'
        }]
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')],
        plugins: ['vux-ui']
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}
module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
})

```
> vueLoader.conf.js配置文件
```
var utils = require('./utils')
var config = require('../config')
var isProduction = process.env.NODE_ENV === 'production'

module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: isProduction
      ? config.build.productionSourceMap
      : config.dev.cssSourceMap,
    extract: isProduction
  }),
  plugins:[{
    name:'vux-ui'
  }]
}

```
> main.js
```
import App from './App';
import VueRouter from 'vue-router';
import VueResource from 'vue-resource';
import Vue from 'vue';

Vue.use(VueRouter);
Vue.use(VueResource);

import goods from 'components/goods/goods';
import ratings from 'components/ratings/ratings';
import seller from 'components/seller/seller';

import 'common/stylus/index.styl';

let routes = [
  {path:'/*',component: goods},
  { path: '/goods', component: goods },
  { path: '/ratings', component: ratings },
  { path: '/seller', component: seller },
];

const router = new VueRouter({
  linkActiveClass:"tab-active",
  routes 
});


const app = new Vue({
  router,
  render:r => r(App)
}).$mount('#app');
```

奇怪的是同样的项目，在别人电脑上可以run。。。
本人新手，望大神指点，感谢！🙏

**Comment by airyland** [comment]
报错信息已经很清楚了，没有这个写法。文档也没有说可以这样写，plugins 是 vux-loader 的写法，上面原来的配置不需要改动任何一行。

![image](https://cloud.githubusercontent.com/assets/559179/25840946/8ddd9a70-34d0-11e7-8b3c-14fd44ff358c.png)

**Comment by AliKhan1990** [comment]
OK了👌，谢谢啦～
