### ISSUE TITLE
Nuxt.js 项目使用 vux，出现 "Unexpected token import" error

### ISSUE THREAD

**Issue by stevenyvette** [airyland/vux#1718]
使用nuxt构建项目时，引入vux组件的时候出现报错如下，使用babel依然无效，请教一下有什么解决方法么？

```
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token import
[vue-router] uncaught error during route navigation:
/Users/gaoyile/github/nuxt/node_modules/vux/index.js:5
import Actionsheet from './src/components/actionsheet/index.vue'
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (/Users/gaoyile/github/nuxt/node_modules/vue-server-renderer/build.js:5812:16)
    at Object.<anonymous> (server-bundle.js:3730:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.82 (1.server-bundle.js:84:12)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.73 (1.server-bundle.js:55:3)
    at __webpack_require__ (server-bundle.js:27:30)
```

**Comment by airyland** [comment]
同样需要在 nuxt 的配置里配置 webpack 使用 vux-loader，但是目前不是所有组件都能支持 ssr 了。

**Comment by stevenyvette** [comment]
@airyland  多谢，问题解决了~

**Comment by heimuya** [comment]
@stevenyvette 请问如何解决的？目前碰到同样的问题

**Comment by weison** [comment]
同样需要在 nuxt 的配置里配置 webpack 使用 vux-loader,可以说说具体是怎么配置吗
