### ISSUE TITLE
打包时报错Tapable.js:357;TypeError: arguments[i].apply is not a function

### ISSUE THREAD

**Issue by panio123** [airyland/vux#1773]
版本信息
``` bash
vux@2.5.4, vux-loader@1.1.4, webpack@2.7.0, node@6.2
```

开发时没有任何提醒或报错，但是打包时会报下面的错误并终止打包。
错误如下：
```bash
node build/build.js

⠋ building for production.../Library/WebServer/Documents/xx/node_modules/tapable/lib/Tapable.js:357
                arguments[i].apply(this);
                             ^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Library/WebServer/Documents/xx/node_modules/tapable/lib/Tapable.js:357:16)
    at webpack (/Library/WebServer/Documents/xx/node_modules/webpack/lib/webpack.js:32:19)
    at err (/Library/WebServer/Documents/xx/build/build.js:18:3)
    at next (/Library/WebServer/Documents/xx/node_modules/rimraf/rimraf.js:74:7)
    at CB (/Library/WebServer/Documents/xx/node_modules/rimraf/rimraf.js:110:9)
    at /Library/WebServer/Documents/xx/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:117:15)
```

我的webpack.base.conf.js 配置如下：(我使用的是vue-cli，除了按vux官方文档要求改了这个配置外，没有修改其它的任何配置了)

``` js
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')

const vuxLoader = require('vux-loader');

function resolve(dir) {
  return path.join(__dirname, '..', dir)
}

var originalConfig = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production' ?
      config.build.assetsPublicPath : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
      'api$': resolve('src/api/index.js')
    }
  },
  module: {
    rules: [{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

module.exports = vuxLoader.merge(originalConfig, {
  plugins: ['vux-ui', {
    name: 'less-theme',
    path: 'src/style/theme.less'
  }]
});

```

npm日志

``` bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle xx@1.0.0~prebuild: xx@1.0.0
6 silly lifecycle xx@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle xx@1.0.0~build: xx@1.0.0
8 verbose lifecycle xx@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle xx@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Library/WebServer/Documents/xx/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle xx@1.0.0~build: CWD: /Library/WebServer/Documents/xx
11 silly lifecycle xx@1.0.0~build: Args: [ '-c', 'node build/build.js' ]
12 silly lifecycle xx@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle xx@1.0.0~build: Failed to exec build script
14 verbose stack Error: xx@1.0.0 build: `node build/build.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid xx@1.0.0
16 verbose cwd /Library/WebServer/Documents/xx
17 error Darwin 16.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error xx@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the xx@1.0.0 build script 'node build/build.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the xx package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/build.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs xx
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls xx
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

目前能想到并提供的内容只有以上这些，如果需要提供其它内容请告知，谢谢了！

**Comment by airyland** [comment]
报错文件并非 vux 源码，所以应该不是 vux 的问题了。

**Comment by airyland** [comment]
看起来是 webpack 的报错，你可以建个 repo 来看看。

**Comment by panio123** [comment]
@airyland  好的，我正在排查是否是vue-cli的问题，很抱歉冒然提到这边来了。

**Comment by panio123** [comment]
我使用vue-cli重新初始化了一个项目，然后把src目录和webpack.base.conf.js拷贝到新项目，竟然就可以打包了。而我这个有问题的项目是在大概两个星期前生成的，这半个月发生了什么就不太好说了。谢谢，打扰了。

**Comment by panio123** [comment]
@airyland 
最终找到问题的原因了，虽然不知道其中的原理。
我把新项目的build文件夹拷贝到覆盖有问题的项目中，然后有问题的项目也可以正常打包了。然后在git显示webpack.prod.conf.js 被改变了，改变的部分正好是一个插件配置
``` js
{
      name: 'duplicate-style',
      events: {
        done: function () {
          console.log('duplicate-style-done!');
        }
      }
```
然后我又把这个插件配置给还原回去，成功复现了报错的问题，所以最终结果是这个插件配置导致的。新的vue-cli项目里把这个去掉了，哈哈。

**Comment by airyland** [comment]
@panio123 收，我检查一下。

**Comment by airyland** [comment]
@panio123 检查了下，vux2 模板里并不会在 prod 配置里加这个插件，这是 vux-loader 的插件，如果你加到 webpack 的 plugin 显然是错误的。

**Comment by TuKun33** [comment]
同，我是webpack-simple的项目，删掉 
```
    {
      name: 'duplicate-style'
    }
```
正常了
