### ISSUE TITLE
npm run build-docs

### ISSUE THREAD

**Issue by fxjs** [airyland/vux#1954]
`
D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:171
  throw generateError(state, message);
  ^
YAMLException: bad indentation of a mapping entry at line 115, column 13:
        params: `(year, month)`
                ^
    at generateError (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readBlockMapping (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1062:11)
    at composeNode (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at load (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Object.safeLoad (D:\vue\vux\node_modules\js-yaml\lib\js-yaml\loader.js:1591:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vux@2.5.11 build-docs: `node build/build-docs.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vux@2.5.11 build-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-09-11T11_49_36_380Z-debug.log`

项目里也新建了 demos文件夹，  这个报错怎么解决呢？

**Comment by airyland** [comment]
检查相应文件  src/components/inline-calendar/metas.yml 115 行的缩进是否不对

**Comment by fxjs** [comment]
从github上下载的最新的可以了 谢谢2017年9月11日 22:48，Airyland <notifications@github.com>写道：检查相应文件  src/components/inline-calendar/metas.yml 115 行的缩进是否不对
