### ISSUE TITLE
Module build failed: Error: Unknown expression type: ExpressionStatement

### ISSUE THREAD

**Issue by Jason2048** [airyland/vux#2078]
package:
		"vue": "^2.4.2",
		"vue-i18n": "^7.3.1",
		"vue-router": "^2.7.0",
		"vuex": "^2.4.0",
		"vuex-i18n": "^1.3.1",
		"vux": "^2.2.1",
		"vux-loader": "^1.0.70",
		"yaml-loader": "^0.4.0",
		"less": "^2.7.1",
		"less-loader": "^2.2.3"

报以下错误：
error  in ./src/App.vue

Module build failed: Error: Unknown expression type: ExpressionStatement
    at generateExpression (/Users/tiangang/workspace/bigbear_platform/node_modules/escodegen/escodegen.js:1527:19)
    at generateExpression (/Users/tiangang/workspace/bigbear_platform/node_modules/escodegen/escodegen.js:1002:24)
    at generateExpression (/Users/tiangang/workspace/bigbear_platform/node_modules/escodegen/escodegen.js:1002:24)
    at generateStatement (/Users/tiangang/workspace/bigbear_platform/node_modules/escodegen/escodegen.js:1666:23)
    at generateStatement (/Users/tiangang/workspace/bigbear_platform/node_modules/escodegen/escodegen.js:2034:21)
    at Object.generate (/Users/tiangang/workspace/bigbear_platform/node_modules/escodegen/escodegen.js:2201:22)
    at generateHTML (/Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/libs/parse-i18n-function.js:7:29)
    at nodes.forEach.one (/Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/libs/parse-i18n-function.js:119:27)
    at Array.forEach (native)
    at parseAttrs (/Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/libs/parse-i18n-function.js:83:9)
    at parse (/Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/libs/parse-i18n-function.js:135:3)
    at Object.<anonymous> (/Users/tiangang/workspace/bigbear_platform/node_modules/vux-loader/libs/parse-i18n-function.js:143:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

 @ ./src/App.vue 10:0-467
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 不知是不是配置的问题，求教。

**Comment by airyland** [comment]
先安装  vux-loader@1.1.13 版本试试。

**Comment by airyland** [comment]
目测应该已经修复，有问题再反馈。
