### ISSUE TITLE
vux-loader 无法加载父级 node_module 路径下安装的 vux

### ISSUE THREAD

**Issue by argent-dawn** [airyland/vux#2357]
## 版本信息
* vux：2.7.5
* vux-loader：1.1.30

## 错误描述
项目的文件结构如下：
```
 |-- node_modules
 |-- scripts
    |-- webpack
       |-- dev.config.js
    |-- tasks
       |-- server.js
 |-- apps
    |-- main
       |-- src
       |-- node_modules      // 空路径
       |-- package.json
    |-- others
       |-- src
       |-- node_modules      // 空路径
       |-- package.json
|-- package.json
```
vux 等相关依赖安装在顶层 node_modules 下，如果在 apps 路径下的项目里尝试构建时，会提示如下错误信息：
```
Error: Cannot find module 'E:\vue\fe-shops-h5\apps\main\node_modules\vux\src\components\map.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Function.module.exports.merge (E:\vue\fe-shops-h5\node_modules\vux-loader\src\index.js:314:18)
    at Object.<anonymous> (E:\vue\fe-shops-h5\scripts\webpack\base.conf.js:146:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\vue\fe-shops-h5\scripts\webpack\dev.conf.js:7:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
 npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! main@1.0.0 serve:dev: `node ../../scripts/tasks/serve.js --dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the main@1.0.0 serve:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by argent-dawn** [comment]
补充:
1. 在子项目 node_modules 路径下安装 vux 可暂时绕过该问题；
2. 在子项目 node_modules 路径下安装 vux 后，还需要同时安装 vue，否则 vux-loader 会报以下错误（类似 #2240）：
```
Module build failed: TypeError: Invalid argument expected string
```
