### ISSUE TITLE
[Bug Report] PopupRadio组件引入就报错

### ISSUE THREAD

**Issue by yuyichen** [airyland/vux#2693]
### VUX version
2.9.0

### OS/Browsers version
win10 / chrome 65.0.3325.181

### Vue version
2.5.2

### Code

```html
import {PopupRadio} from 'vux'

```

### Steps to reproduce
引入PopupRadio组件,编译报错,去掉引入恢复正常

### What is Expected?
正常使用

### What is actually happening?
Failed to compile.

./node_modules/_babel-loader@7.1.4@babel-loader/lib!./node_modules/_vux-loader@1.2.8@vux-loader/src/script-loader.js!./node_modules/_vux-loader@1.2.8@vux-loader/src/script-loader.js!./node_modules/_vue-loader@13.7.1@vue-loader/lib/selector.js?type=script&index=0!./node_modules/_vux@2.9.0@vux/src/components/popup-radio/index.vue
Module build failed: TypeError: F:/workspace/ent_admin_h5/node_modules/_vux@2.9.0@vux/src/components/popup-radio/index.vue: Cannot read property 'value' of undefined
    at getName (F:\workspace\ent_admin_h5\node_modules\_babel-plugin-transform-es2015-duplicate-keys@6.24.1@babel-plugin-transform-es2015-duplicate-keys\lib\index.js:85:14)
    at PluginPass.ObjectExpression (F:\workspace\ent_admin_h5\node_modules\_babel-plugin-transform-es2015-duplicate-keys@6.24.1@babel-plugin-transform-es2015-duplicate-keys\lib\index.js:41:22)
    at newFn (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\index.js:114:17)
    at NodePath.visit (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\index.js:114:17)
    at NodePath.visit (F:\workspace\ent_admin_h5\node_modules\_babel-traverse@6.26.0@babel-traverse\lib\path\context.js:115:19)
 @ ./node_modules/_vux@2.9.0@vux/src/components/popup-radio/index.vue 8:0-241
 @ ./node_modules/_babel-loader@7.1.4@babel-loader/lib!./node_modules/_vux-loader@1.2.8@vux-loader/src/script-loader.js!./node_modules/_vux-loader@1.2.8@vux-loader/src/script-loader.js!./node_modules/_vue-loader@13.7.1@vue-loader/lib/selector.js?type=script&index=0!./src/views/baseInfo/BaseInfo.vue
 @ ./src/views/baseInfo/BaseInfo.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

**Comment by CongjiZhu** [comment]
I have the same problem，When I use 'PopupRadio.vue', It will throw out Error:

"This dependency was not found in node_modules:
* vux/undefined
Did you forget to run npm install --save for it?"

If you have solved it, tell me the trouble，My Email is 791984535@qq.com. Thanks

**Comment by CongjiZhu** [comment]
This dependency was not found in node_modules:

* vux/undefined

Did you forget to run npm install --save for it?

**Comment by CongjiZhu** [comment]
I have the same problem，When I use 'PopupRadio.vue', It will throw out Error:

"This dependency was not found in node_modules:

vux/undefined
Did you forget to run npm install --save for it?"
If you have solved it, tell me the trouble，My Email is 791984535@qq.com. Thanks
