### ISSUE TITLE
[Bug Report] Vux 2.7.7升级到2.9.1之后，没改任何配置，出现Unexpected token export

### ISSUE THREAD

**Issue by z-hao** [airyland/vux#2778]
### VUX version
2.9.1

### OS/Browsers version
MAC OS / Chrome

### Vue version
2.5.13

### Code

```html
我使用的是nuxtjs, 在nuxt.config.js配置如下（升级Vux 2.7.7至2.9.1没有任何改动，2.7.7版本是正常的）
build: {
    extend (config, ctx) {
      VuxLoader.merge(config, {
        plugins: [
          { name: 'vux-ui' },
          { name: 'less-theme', path: 'assets/vux-variable.less' },
          { name: 'duplicate-style' }
        ]
      })
    }
  },
```

### Steps to reproduce
运行时

### What is Expected?
babel能正常工作

### What is actually happening?
babel没能正常编译

**Comment by airyland** [comment]
所以 Unexpected token export 是哪个文件报的错？
有没有用 yarn 锁版本，更大可能是 vue vue-loader 版本跟之前不一致了，先试试升级  vux-loader。

**Comment by z-hao** [comment]
报错文件
```
/node_modules/vux/src/directives/transfer-dom/index.js:100
export default directive

SyntaxError: Unexpected token export
```
我把yarn.lock删了，重新yarn了一次，同样的问题。我查了一下vux-loader的版本是最新的1.2.8，vue的版本是2.5.16。我尝试把vux降级到2.7.7, 2.7.9都没问题，但是从2.8.0开始报这个错 @airyland 。目前我还在继续查

**Comment by lainazy** [comment]
``` bash
ERROR  Failed to compile with 1 errors                                 17:02:48

 error  in ./node_modules/vux/src/components/v-chart/mixin.js

Module parse failed: Unexpected token (18:6)
You may need an appropriate loader to handle this file type.
|     this.$parent.set(this.chartName, {
|       shape: defaultShapeMap[this.chartName] || '',
|       ...this.$props,
|       ...camelAttrs(this.$attrs)
|     })
```

我这边也有类似问题，貌似2.9.1不支持es6里面的一些新语法糖，我这边是`...`报的错，但是我自己的其他项目文件里面用这个`...`是ok的，在vux文件中使用就不行。

引入x-header使用时会报这个错

**Comment by guotie** [comment]
类似的错误：
```
Server listening on http://127.0.0.1:3000
{ /Users/mengyangzhang/Projects/meiyoung/mei/node_modules/vux/src/plugins/loading/index.js:1
(function (exports, require, module, __filename, __dirname) { import LoadingComponent from '../../components/loading'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at r (/Users/mengyangzhang/Projects/meiyoung/mei/node_modules/vue-server-renderer/build.js:8341:16)
    at Object.<anonymous> (server-bundle.js:4233:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 154a6182fe47780c8c01:25:0)
    at Object.<anonymous> (plugins/vux.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 154a6182fe47780c8c01:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 154a6182fe47780c8c01:25:0) statusCode: 500, name: 'SyntaxError' }

```

package.json:

```
{
  "name": "meiyoung",
  "version": "1.0.0",
  "description": "meiyoung",
  "author": "guotie",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server/index.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.0.0",
    "@nuxtjs/bulma": "^1.0.3",
    "axios": "^0.18.0",
    "babel-plugin-component": "^1.1.1",
    "es6-promise": "^4.2.4",
    "fastclick": "^1.0.6",
    "js-cookie": "^2.2.0",
    "jwt-decode": "^2.2.0",
    "koa": "^2.3.0",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "nuxt": "^1.0.0",
    "vuex-persistedstate": "^2.5.4",
    "vux": "^2.9.2",
    "vux-loader": "^1.2.9"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^21.0.2",
    "babel-loader": "^7.1.1",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "cors": "^2.8.4",
    "cross-env": "^5.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "fastify": "^1.10.0",
    "fastify-cookie": "^2.0.1",
    "fastify-formbody": "^2.0.1",
    "fastify-static": "^0.14.0",
    "fastify-xml-body-parser": "^1.0.3",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "lodash": "^4.17.10",
    "nodemon": "^1.11.0"
  }
}

```

**Comment by wwz348627642** [comment]
小的先把export default directive 改成了module.exports = directive，没报错，先将就着用

**Comment by JakeVivit** [comment]
出现同样的问题   D:\zhangchong\SSR\ssr-demo\ssr-nuxt-express\node_modules\vux\src\plugins\alert\module.js:1报错： (function (exports, require, module, __filename, __dirname) { import Vue from 'vue'

**Comment by axetroy** [comment]
下载完之后，我是手动编译的

```bash
$ npm install babel-preset-env --dev
```

加进 ``package.json``

```json
  {
    "fix": "npx babel-cli ./node_modules/vux/src --presets=env --out-dir ./node_modules/vux/src --copy-files --source-maps inline",
    "postinstall": "npm run fix"
  }

```
