### ISSUE TITLE
[Bug Report] clone 项目以后 run dev 报错

### ISSUE THREAD

**Issue by azumia** [airyland/vux#2779]
### VUX version
2.9.1

### OS/Browsers version
win10/ chrome 66

### Vue version
2.5.16

### Code

```html

Module build failed: Error: ENOENT: no such file or directory, open 'E:\pwork\vux\src\demos\E:\pwork\vux\src\demos\countdown\basic.vue'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at glob.sync.filter.map.one (E:\pwork\vux\build\vux-config.js:79:27)
    at Array.map (<anonymous>)
    at Object.fn (E:\pwork\vux\build\vux-config.js:66:12)
    at E:\pwork\vux\node_modules\vux-loader\src\js-loader.js:43:32
    at Array.forEach (<anonymous>)
    at Object.module.exports (E:\pwork\vux\node_modules\vux-loader\src\js-loader.js:38:23)
```

### Steps to reproduce
git clone ...
npm install
npm run dev

### What is Expected?
项目能够跑起来

### What is actually happening?
报错

**Comment by lichunqiang** [comment]
Duplicated: #2781
