### ISSUE TITLE
[Bug Report] 项目clone本地运行报错

### ISSUE THREAD

**Issue by zhenjingbo** [airyland/vux#2781]
### VUX version
2.9.1

### OS/Browsers version
node

### Vue version
2.5.17-beta.0

### Code

```html
W
 ERROR  Failed to compile with 1 errors                                                                                                                                                           16:11:06

 error  in ./src/main.js

Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\ASUS\Desktop\vux-2\src\demos\C:\Users\ASUS\Desktop\vux-2\src\demos\countdown\basic.vue'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at glob.sync.filter.map.one (C:\Users\ASUS\Desktop\vux-2\build\vux-config.js:79:27)
    at Array.map (<anonymous>)
    at Object.fn (C:\Users\ASUS\Desktop\vux-2\build\vux-config.js:66:12)
    at C:\Users\ASUS\Desktop\vux-2\node_modules\vux-loader\src\js-loader.js:43:32
    at Array.forEach (<anonymous>)
    at Object.module.exports (C:\Users\ASUS\Desktop\vux-2\node_modules\vux-loader\src\js-loader.js:38:23)

 @ multi (webpack)-dev-server/client?http://0.0.0.0:8082 webpack/hot/dev-server ./src/main.js
```

### Steps to reproduce
npm run dev

### What is Expected?
运行不会报错

### What is actually happening?
运行报错

**Comment by airyland** [comment]
大概是 windows 系统的关系，暂时没有 windows 环境，待检查。

**Comment by rockedpanda** [comment]
昨天在windows下遇到相同问题，定位确实是操作系统对路径的 \ 与 / 处理不一致导致。
今天就看到了PR，感谢。

**Comment by azumia** [comment]
@rockedpanda 请问一下这个怎么解决？

**Comment by lichunqiang** [comment]
@azumia 拉下最新的代码，然后更新下依赖

**Comment by azumia** [comment]
@lichunqiang 可以了，谢谢
