### ISSUE TITLE
[Feature Request] 可否支持vue-hackernews-2.0?

### ISSUE THREAD

**Issue by NoraGithub** [airyland/vux#2912]
### Existing Component
否

### Component Name
https://github.com/vuejs/vue-hackernews-2.0/

### Description
目前使用 vue-hackernews-2.0 进行SSR 渲染，显示 错误：
```
webpack built cb325306a009ba240a10 in 8690ms
error during render : /top
/Users/NoraChan/Desktop/test/vue-hackernews-2.0/node_modules/vux/src/components/tabbar/tabbar.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/Users/NoraChan/Desktop/test/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:8330:16)
```

看起来原因是vue没有解析(即，**vux-loader可能有bug？因为都配置了**)。公司项目比较早期，没有使用nuxt，可否支持下该项目的ssr？相关项目。https://github.com/airyland/vux/issues/2131

**Comment by NoraGithub** [comment]
git clone 官方下载后，降级vue-loader到14.2.3 并使用 vux-loader 。

文件修改如下：

```
diff --git a/.babelrc b/.babelrc
index 4f95cb0..0fcce9a 100644
--- a/.babelrc
+++ b/.babelrc
@@ -1,8 +1,18 @@
 {
   "presets": [
-    ["env", { "modules": false }]
+    ["env", { "modules": false,
+    "targets": {
+        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"],
+        "node":"current",
+        "forceAllTransforms": true
+      } }]
   ],
   "plugins": [
-    "syntax-dynamic-import"
+    "syntax-dynamic-import",["transform-runtime", {
+                    "helpers": false,
+                    "polyfill": false,
+                    "regenerator": true,
+                    "moduleName": "babel-runtime"
+                  }]
   ]
 }
diff --git a/build/webpack.base.config.js b/build/webpack.base.config.js
index 2427e22..dc60416 100644
--- a/build/webpack.base.config.js
+++ b/build/webpack.base.config.js
@@ -2,7 +2,6 @@ const path = require('path')
 const webpack = require('webpack')
 const ExtractTextPlugin = require('extract-text-webpack-plugin')
 const FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')
-const { VueLoaderPlugin } = require('vue-loader')
 
 const isProd = process.env.NODE_ENV === 'production'
 
@@ -18,7 +17,8 @@ module.exports = {
   resolve: {
     alias: {
       'public': path.resolve(__dirname, '../public')
-    }
+    },
+    extensions: ['.js', '.vue', '.json']
   },
   module: {
     noParse: /es6-promise\.js$/, // avoid webpack shimming process
@@ -68,7 +68,6 @@ module.exports = {
   },
   plugins: isProd
     ? [
-        new VueLoaderPlugin(),
         new webpack.optimize.UglifyJsPlugin({
           compress: { warnings: false }
         }),
@@ -78,7 +77,6 @@ module.exports = {
         })
       ]
     : [
-        new VueLoaderPlugin(),
         new FriendlyErrorsPlugin()
       ]
 }
diff --git a/build/webpack.client.config.js b/build/webpack.client.config.js
index 9a75475..eae968b 100644
--- a/build/webpack.client.config.js
+++ b/build/webpack.client.config.js
@@ -3,6 +3,8 @@ const merge = require('webpack-merge')
 const base = require('./webpack.base.config')
 const SWPrecachePlugin = require('sw-precache-webpack-plugin')
 const VueSSRClientPlugin = require('vue-server-renderer/client-plugin')
+const vuxLoader = require('vux-loader')
+
 
 const config = merge(base, {
   entry: {
@@ -72,4 +74,26 @@ if (process.env.NODE_ENV === 'production') {
   )
 }
 
-module.exports = config
+module.exports = vuxLoader.merge(config, {
+  plugins: [
+    'vux-ui',
+    'progress-bar',
+    {
+      name: 'duplicate-style',
+      options: {
+        cssProcessorOptions : {
+          safe: true,
+          zindex: false,
+          autoprefixer: {
+            add: true,
+            browsers: [
+              'iOS >= 7',
+              'Android >= 4.1'
+            ]
+          }
+        }
+      }
+    }
+  ]
+})
+
diff --git a/build/webpack.server.config.js b/build/webpack.server.config.js
index 615e6a3..b3bcd80 100644
--- a/build/webpack.server.config.js
+++ b/build/webpack.server.config.js
@@ -3,8 +3,10 @@ const merge = require('webpack-merge')
 const base = require('./webpack.base.config')
 const nodeExternals = require('webpack-node-externals')
 const VueSSRServerPlugin = require('vue-server-renderer/server-plugin')
+const vuxLoader = require('vux-loader')
 
-module.exports = merge(base, {
+
+config = merge(base, {
   target: 'node',
   devtool: '#source-map',
   entry: './src/entry-server.js',
@@ -31,3 +33,26 @@ module.exports = merge(base, {
     new VueSSRServerPlugin()
   ]
 })
+
+module.exports = vuxLoader.merge(config, {
+  plugins: [
+    'vux-ui',
+    'progress-bar',
+    {
+      name: 'duplicate-style',
+      options: {
+        cssProcessorOptions : {
+          safe: true,
+          zindex: false,
+          autoprefixer: {
+            add: true,
+            browsers: [
+              'iOS >= 7',
+              'Android >= 4.1'
+            ]
+          }
+        }
+      }
+    }
+  ]
+})
diff --git a/package.json b/package.json
index 6253725..91260ba 100644
--- a/package.json
+++ b/package.json
@@ -40,17 +40,20 @@
     "css-loader": "^0.28.7",
     "file-loader": "^1.1.5",
     "friendly-errors-webpack-plugin": "^1.6.1",
+    "less": "^3.5.3",
+    "less-loader": "^4.1.0",
     "rimraf": "^2.6.2",
     "stylus": "^0.54.5",
     "stylus-loader": "^3.0.1",
     "sw-precache-webpack-plugin": "^0.11.4",
     "url-loader": "^0.6.2",
-    "vue-loader": "^15.0.0-beta.1",
+    "vue-loader": "^14.2.3",
     "vue-template-compiler": "^2.5.16",
     "webpack": "^3.8.1",
     "webpack-dev-middleware": "^1.12.0",
     "webpack-hot-middleware": "^2.20.0",
     "webpack-merge": "^4.1.1",
-    "webpack-node-externals": "^1.6.0"
+    "webpack-node-externals": "^1.6.0",
+    "yaml-loader": "^0.5.0"
   }
 }
diff --git a/src/App.vue b/src/App.vue
index ff8643c..0bfc31e 100644
--- a/src/App.vue
+++ b/src/App.vue
@@ -18,9 +18,18 @@
     <transition name="fade" mode="out-in">
       <router-view class="view"></router-view>
     </transition>
+    <tabbar></tabbar>
   </div>
 </template>
-
+<script>
+  import { Tabbar, TabbarItem } from 'vux'
+  export default {
+    components:{
+      Tabbar,
+      TabbarItem
+    }
+  }
+</script>
 <style lang="stylus">
 body
   font-family -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
@@ -100,3 +109,6 @@ a
     .github
       display none
 </style>
+<style lang="less">
+@import '~vux/src/styles/reset.less';
+</style>
```
