### ISSUE TITLE
import Actionsheet from './src/components/actionsheet/index.vue'

### ISSUE THREAD

**Issue by soberlyxq** [airyland/vux#2968]
import Actionsheet from './src/components/actionsheet/index.vue'
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at r (D:\workspace\git\YoexMobile\node_modules\vue-server-renderer\build.js:7739:16)
    at Object.89 (webpack:/external "vux":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 0a671c5070ed2a81f13b:25:0)
    at Object.88 (server-bundle.js:4552:62)
    at __webpack_require__ (webpack:/webpack/bootstrap 0a671c5070ed2a81f13b:25:0)
    at Object.37 (server-bundle.js:2064:67)
    at __webpack_require__ (webpack:/webpack/bootstrap 0a671c5070ed2a81f13b:25:0)

大神，NUXT中引入报这个错。    "vux-loader": "^1.2.1"     "vux": "^2.9.2"

**Comment by soberlyxq** [comment]
console.warn('VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。')
   vux-loader 升到1.2.9   eslint 也是 standard
