### ISSUE TITLE
Vux真的太牛了，下一个项目要正式使用了，官方可否提供CDN链接？

### ISSUE THREAD

**Issue by duruitang** [airyland/vux#308]
如题，如果有CDN那就太完美了。
当然，提交到第三方CDN库也十分好啊，如：http://www.bootcdn.cn

**Comment by airyland** [comment]
暂时没有。其实也不推荐用cdn, 用.vue组件更合适。

**Comment by duruitang** [comment]
嗯，支持你们！如果有CDN就更完美了！

请问官方有类似赞赏的支付宝或微信吗？有时间的话想赞赏你们一点微薄之力~

**Comment by LiangFuzhi** [comment]
https://vux.li/?x-page=github_readme#!/project/donate

**Comment by airyland** [comment]
vux.li 首页有链接 😄

**Comment by airyland** [comment]
补充一下，如果用于测试可以直接用 npmcdn
https://npmcdn.com/vux@0.1.1/dist/vux.js
https://npmcdn.com/vux@0.1.1/dist/vux.css

**Comment by funCfans** [comment]
关于npmcdn，我index.html引入了这两个链接，并且把package.json的vux版本说明和node_modules里面的vux目录删除了，结果提示错误：

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'node_modules\vux\src\components\map.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.module.exports.merge (D:\myVues\task_resource_group\node_modules\vux-loader\src\index.js:334:18)
    at Object.<anonymous> (D:\myVues\task_resource_group\build\webpack.base.conf.js:120:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
