### ISSUE TITLE
[Bug Report] vue-cli3 router config lazy loading throw 'Cannot read property 'vuxVariableMap' of undefined'

### ISSUE THREAD

**Issue by Evansy** [airyland/vux#3108]
### VUX version
2.9.2

### OS/Browsers version
win10/chrome 69

### Vue version
2.5.17

### Code

```html
```js
// vue.config.js 
const path = require("path");
const vuxLoader = require("vux-loader");

module.exports = {
    baseUrl: "",
    configureWebpack: config => {
        vuxLoader.merge(
            config,
            {
                resolve: {
                    alias: {
                        vue$: "vue/dist/vue.esm.js",
                        "src": path.resolve(__dirname, "./src"),
                        "assets": path.resolve(__dirname, "./src/assets"),
                        "components": path.resolve(__dirname, "./src/components"),
                        "scss": path.resolve(__dirname, "./src/scss"),
                        "router": path.resolve(__dirname, "./src/router"),
                        "stores": path.resolve(__dirname, "./src/stores"),
                        "views": path.resolve(__dirname, "./src/views"),
                        "common": path.resolve(__dirname, "./src/common")
                    }
                }
            },
            {
                plugins: ["vux-ui"]
            }
        );
    }
};
```
when i config vue routes like that:
```js
import Vue from 'vue';
import Router from 'vue-router';

// const Home = () => import(/* webpackChunkName: "home" */ '../views/home.vue');
const Home = () => import('../views/home.vue').then(m => m.default)

Vue.use(Router);

export default new Router({
    base: process.env.BASE_URL,
    routes: [
        {
            path: '*',
            redirect: '/home'
        },
        {
            path: '/home',
            name: 'home',
            meta: {
                navActiveIndex: 0
            },
            component: Home
        },
    ]
});
```
i'm try to use`const Home = () => import(/* webpackChunkName: "home" */ '../views/home.vue');`, it still can't work...

errro message like that:
```js
error  in ./src/App.vue

Module build failed (from ./node_modules/vux-loader/src/index.js):
TypeError: Cannot read property 'vuxVariableMap' of undefined
    at Object.exports.getLoaderConfig (F:\newlife\qianzj\node_modules\vux-loader\node_modules\loader-utils\index.js:124:37)
    at Object.module.exports (F:\newlife\qianzj\node_modules\vux-loader\src\index.js:67:52)

 @ ./src/main.js 5:0-28 14:13-16
 @ multi (webpack)-dev-server/client?http://192.168.1.3:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
 error  in ./src/views/home.vue

Module build failed (from ./node_modules/vux-loader/src/index.js):
TypeError: Cannot read property 'vuxVariableMap' of undefined
    at Object.exports.getLoaderConfig (F:\newlife\qianzj\node_modules\vux-loader\node_modules\loader-utils\index.js:124:37)
    at Object.module.exports (F:\newlife\qianzj\node_modules\vux-loader\src\index.js:67:52)

 @ ./src/router/index.js 11:9-36
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.3:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
```

### Steps to reproduce
1. use the latest vue-cli
2. config `vux-loader` in `vue.config.js`
3. config lazy loading components

### What is Expected?
fix this bug.

### What is actually happening?
can not work.

<!-- generated by https://doc.vux.li/issue-generator DO NOT REMOVE -->

**Comment by liguangshuai1997** [comment]
I also encountered this problem when using the egg+vue project.I do not know how to solve this

**Comment by guoliangli123** [comment]
我遇到了同样的问题，vue-cli 3配置vux插件出错，作者说不兼容，但是有没有解决办法啊？
