### ISSUE TITLE
Android和IOS webview使用x-input组件type="number"录入数字就报错，vux版本为2.9.2，vue版本为2.5.13

### ISSUE THREAD

**Issue by xhhcocos2d** [airyland/vux#3125]
DOMException: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.
    at VueComponent.currentValue (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules…=script&index=0!./node_modules/vux/src/components/x-input/index.vue:582:39)
    at Watcher.run (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3232:19)
    at flushSchedulerQueue (webpack-internal:///./node_modules/vue/dist/vue.esm.js:2980:13)
    at Array.eval (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1836:12)
    at MessagePort.flushCallbacks (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1757:14)

**Comment by Jiiiiiin** [comment]
👍

**Comment by cappusd3** [comment]
t同问

**Comment by xhhcocos2d** [comment]
我自己把源码给改了😂😂

Kevin Chan <notifications@github.com> 于2018年9月26日周三 上午10:46写道：
