### ISSUE TITLE
[Bug Report] 在nuxt中使用，组件无法通过npm run dev，loader报错

### ISSUE THREAD

**Issue by xlkit456852** [airyland/vux#3333]
### VUX version
2.9.2

### OS/Browsers version
win10/Chrome 版本 71.0.3578.98（正式版本） （32 位）

### Vue version
2.5.21

### Code

```html
package.json
```
"dependencies": {
    "@nuxtjs/axios": "^5.0.0",
    "cross-env": "^5.2.0",
    "express": "^4.16.3",
    "nuxt": "^2.0.0",
    "vux": "^2.9.2"
  },
  "devDependencies": {
    "babel-preset-env": "^1.7.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "nodemon": "^1.11.0",
    "vux-loader": "^1.2.9"
  }
```

nuxt.config.js
与https://github.com/airyland/vux/tree/v2/ssr/nuxt给出的例子一样
```

### Steps to reproduce
按照https://github.com/airyland/vux/tree/v2/ssr/nuxt给出的例子进行配置，然后npm run dev，出现好多个：
```
> log friendly-errors »
 @ ./node_modules/vux/index.js 60:0-49 166:0-327:1
 @ ./plugins/vux/vux-components.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr/client ./.nuxt/client.j
s
× error friendly-errors » in ./node_modules/vux/src/components/grid/grid-item.vue
> log friendly-errors » Module parse failed: Unexpected token (3:0)
You may need an appropriate loader to handle this file type.
| import { render, staticRenderFns } from "./grid-item.vue?vue&type=template&id=5fee7ff2&"
| import script from "./grid-item.vue?vue&type=script&lang=js&"
> ../../../../vux-loader/src/script-loader.js!export * from "./grid-item.vue?vue&type=script&lang=js&"
| import style0 from "./grid-item.vue?vue&type=style&index=0&lang=less&"
```

好像基本上都是说loader不正确

### What is Expected?
npm run dev应该至少能通过才能做后续的开发。

### What is actually happening?
npm run dev无法通过。

**Comment by missleeee** [comment]
我也遇到同样的问题

**Comment by hopkinson** [comment]
请问解决了吗

**Comment by dfang** [comment]
+1

**Comment by yorsal** [comment]
> ### VUX version
> 2.9.2
> 
> ### OS/Browsers version
> win10/Chrome 版本 71.0.3578.98（正式版本） （32 位）
> 
> ### Vue version
> 2.5.21
> 
> ### Code
> ```
> package.json
> ```
> 
> "dependencies": {
> "@nuxtjs/axios": "^5.0.0",
> "cross-env": "^5.2.0",
> "express": "^4.16.3",
> "nuxt": "^2.0.0",
> "vux": "^2.9.2"
> },
> "devDependencies": {
> "babel-preset-env": "^1.7.0",
> "less": "^3.9.0",
> "less-loader": "^4.1.0",
> "nodemon": "^1.11.0",
> "vux-loader": "^1.2.9"
> }
> 
> ```
> 
> nuxt.config.js
> 与https://github.com/airyland/vux/tree/v2/ssr/nuxt给出的例子一样
> ```
> ### Steps to reproduce
> 按照[https://github.com/airyland/vux/tree/v2/ssr/nuxt给出的例子进行配置，然后npm](https://github.com/airyland/vux/tree/v2/ssr/nuxt%E7%BB%99%E5%87%BA%E7%9A%84%E4%BE%8B%E5%AD%90%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE%EF%BC%8C%E7%84%B6%E5%90%8Enpm) run dev，出现好多个：
> 
> ```
> > log friendly-errors »
>  @ ./node_modules/vux/index.js 60:0-49 166:0-327:1
>  @ ./plugins/vux/vux-components.js
>  @ ./.nuxt/index.js
>  @ ./.nuxt/client.js
>  @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr/client ./.nuxt/client.j
> s
> × error friendly-errors » in ./node_modules/vux/src/components/grid/grid-item.vue
> > log friendly-errors » Module parse failed: Unexpected token (3:0)
> You may need an appropriate loader to handle this file type.
> | import { render, staticRenderFns } from "./grid-item.vue?vue&type=template&id=5fee7ff2&"
> | import script from "./grid-item.vue?vue&type=script&lang=js&"
> > ../../../../vux-loader/src/script-loader.js!export * from "./grid-item.vue?vue&type=script&lang=js&"
> | import style0 from "./grid-item.vue?vue&type=style&index=0&lang=less&"
> ```
> 好像基本上都是说loader不正确
> 
> ### What is Expected?
> npm run dev应该至少能通过才能做后续的开发。
> 
> ### What is actually happening?
> npm run dev无法通过。

因为最新的nuxt早就是webpack4.0了，vux不支持webpack4.0，所以loader会报错

**Comment by yorsal** [comment]
> 请问解决了吗

package.json 里把 nuxt 里的lastest改为 1.4.2， 只能降级到1.x的最后一个版本，也就是升级到webpack4.0 前一个版本

**Comment by xlkit456852** [comment]
希望能够支持webpack4.0，vux很好，一直在用呢。不到迫不得已不想用其他ui框架~~

**Comment by rumengkai** [comment]
我也遇到问题过来啦，看来短时间支持不了webpack4了，vux挺好的，但我在nuxt中先使用MintUI了

**Comment by LvJianfeng** [comment]
+1

**Comment by LuckLin520** [comment]
这个问题我找了三天原因，试了n种方法，百度都没有找到原因，终于还是在这找到了。。我的青春啊

**Comment by LuckLin520** [comment]
> > 请问解决了吗
> 
> package.json 里把 nuxt 里的lastest改为 1.4.2， 只能降级到1.x的最后一个版本，也就是升级到webpack4.0 前一个版本
大哥，我换成nuxt1.4.2后又报错：
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'consola'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/nginx/servers-container/nuxtapp/server/index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
