### ISSUE TITLE
[Bug Report] 本地查看文档问题

### ISSUE THREAD

**Issue by xfmbyc** [airyland/vux#3401]
### VUX version
2.9.2

### OS/Browsers version
win10  /  chrome 71.0.3578.98（正式版本） （64 位）

### Vue version
2.6.7

### Code

```html
D:\VUX-DEMO\vux>npm run doc:build

> vux@2.9.2 doc:build D:\VUX-DEMO\vux
> node build/build-docs.js && node docs/component-contributors && node docs/compile

undefined:1
['format:{hash:9f73763424617817aefadc20c2f82d8cf344509d,authorName:airyland,authorEmail:airyland@qq.com,date:2018-04-29T02:06:29 08:00},' 'format:{hash:a492017e414682adaf39d8c9a5c8d47b39ea17d6,authorName:jiangling,authorEmail:ftium4@gmail.com,date:2018-04-29T22:16:02 08:00},' 'format:{hash:bf7cb9ac9fc5ac375faaa4e533d624f85e9f5d64,authorName:jiangling,authorEmail:ftium4@gmail.com,date:2018-04-29T22:05:59 08:00},' 'format:{hash:9060fa49c80c8221f74aa698ce120d133c49d259,authorName:zhangzicao,authorEmail:729300423@qq.com,date:2018-04-19T08:55:19 08:00},' 'format:{hash:73355be393cc35995a362afa4f45eabacef69129,authorName:airyland,authorEmail:airyland@qq.com,date:2018-04-16T20:47:00 08:00},' 'format:{hash:90694e5cbd8387508f9e35e0ac64d455c7c5b281,authorName:airyland,authorEmail:airyland@qq.com,date:2018-04-16T03:38:45 08:00},' 'format:{hash:09cb46c0f180ab8f4b8a41d58041f8ae272f310a,authorName:airyland,authorEmail:airyland@qq.com,date:2017-11-22T10:41:24 08:00},' 'format:{hash:e7146d09d030587a17df77629b059

SyntaxError: Unexpected token ' in JSON at position 1
    at JSON.parse (<anonymous>)
    at components.map.forEach.one (D:\VUX-DEMO\vux\docs\component-contributors.js:26:14)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\VUX-DEMO\vux\docs\component-contributors.js:19:54)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vux@2.9.2 doc:build: `node build/build-docs.js && node docs/component-contributors && node docs/compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vux@2.9.2 doc:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-01T07_38_13_303Z-debug.log



D:\VUX-DEMO\vux\docs>node compile
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\VUX-DEMO\vux\docs\.D:\VUX-DEMO\vux\docs\en\faq\$t-is-not-defined.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at faqs.forEach.one (D:\VUX-DEMO\vux\docs\compile.js:167:24)
    at Array.forEach (<anonymous>)
    at langs.forEach.lang (D:\VUX-DEMO\vux\docs\compile.js:165:8)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\VUX-DEMO\vux\docs\compile.js:154:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

### Steps to reproduce
按照文档说明，在执行npm run doc:build 构建文档时出错，如上。 执行node compile 时报错，如上

### What is Expected?
修复

### What is actually happening?
修复

**Comment by JackgorHJ** [comment]
您好，请问我在Vux项目 npm run build 也出现错误.
请问应该怎么打包才不会出现错误呢？


static/css/app.6bedbae377a4fa9dfa3c31ece9602796.css    42.7 kB     142  [emitted]         app
                                         index.html    6.29 kB          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vux@2.9.2 build: `node build/build.js && rimraf docs/demos/v2/ && mkdirp docs/demos/v2 && cp -r docs/demos/temp/* docs/demos/v2/`npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vux@2.9.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\IVC\AppData\Roaming\npm-cache\_logs\2019-03-12T07_58_16_883Z-debug.log

**Comment by tanyichao2017** [comment]
遇到同样的问题，有解决吗？

**Comment by caozhong1996** [comment]
之后想办法把文档放到github page 或者gitee上吧
