### ISSUE TITLE
[Bug Report] 无法本地构建docs文档。

### ISSUE THREAD

**Issue by tanyichao2017** [airyland/vux#3518]
### VUX version
2.9.4

### OS/Browsers version
windows/Google-chrome 75版本

### Vue version
2.6.10

### Code

```html
F:\code\vux2\docs>node compile
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'F:\code\vux2\docs\.F:\code\vux2\docs\en\faq\$t-is-not-defined.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at faqs.forEach.one (F:\code\vux2\docs\compile.js:167:24)
    at Array.forEach (<anonymous>)
    at langs.forEach.lang (F:\code\vux2\docs\compile.js:165:8)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (F:\code\vux2\docs\compile.js:154:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

### Steps to reproduce
yarn 
cd docs
node compile

### What is Expected?
能够正确的构建本地文档，

### What is actually happening?
目前构建本地文档报错

**Comment by kevinchung1026** [comment]
`cd docs`之后再`yarn`或`npm install`一次，再试试`npm compile`

**Comment by tanyichao2017** [comment]
@kevinchung1026  目前就是按照这个流程 你本地能构建出来吗？ 能否发一份静态文件到xiaosha5447@163.com 多谢

**Comment by kevinchung1026** [comment]
我可以构建啊，你要哪些文件？

**Comment by tanyichao2017** [comment]
@kevinchung1026  可以把完整的文档发给我邮箱吗？就是这个https://doc.vux.li/zh-CN/的文档， 感谢前辈 邮箱底子xiaosha5447@163.com

**Comment by tanyichao2017** [comment]
有人可以帮忙吗？

**Comment by justorez** [comment]
是 Windows 路径分隔符导致的问题：斜杠和反斜杠混用了，导致后面文件路径字符串执行`replace`时，都不生效了，所以产生了你贴出来的很奇怪的路径。需要修改一下`docs/compile.js`。
在文件第二行，添上这句代码：
```javascript
__dirname = __dirname.replace(/\\/g,'/')
```
然后`getPath`函数修改为：
```javascript
const getPath = function (dir) {
  return path.join(__dirname, dir).replace(/\\/g,'/')
}
```
改完后，我执行`node docs/compile`就没问题了。
