### ISSUE TITLE
vue-cli3项目中，build时候vux/loader 报错

### ISSUE THREAD

**Issue by MonsterGoGoGo** [airyland/vux#3687]
我的vue.config.js配置
```
  configureWebpack: config => {
    require('@vux/loader').merge(config, {
      plugins: ['vux-ui']
    })
  }
```
vux及vux-loader版本    
```
"vux": "^2.9.4",
"vux-loader": "^1.2.9"
```

npm run serve/build 时报错如下内容

```
Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
```
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
```
See https://babeljs.io/docs/en/options#filename for more information.
    at validateIfOptionNeedsFilename (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/config/full.js:254:11)
    at options.overrides.forEach.overrideOptions (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/config/full.js:266:52)
    at Array.forEach (<anonymous>)
    at validatePreset (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/config/full.js:266:25)
    at loadPresetDescriptor (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/config/full.js:273:3)
    at loadPresetDescriptor.next (<anonymous>)
    at recurseDescriptors (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/config/full.js:94:28)
    at recurseDescriptors.next (<anonymous>)
    at loadFullConfig (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/config/full.js:122:6)
    at loadFullConfig.next (<anonymous>)
    at Function.transform (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/transform.js:25:45)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/gensync/index.js:244:28)
    at Function.sync (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/gensync/index.js:84:14)
    at Object.transform (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@babel/core/lib/transform.js:36:54)
    at transform (/Users/gaodan/Desktop/code/recruit-erp-mobile/node_modules/@vux/loader/src/libs/import-parser-v2.js:7:19)
```
这个是什么原因~有好的办法解决吗

**Comment by wudimenghuan** [comment]
同样出现这个问题了

**Comment by caozhong1996** [comment]
see #3778
