### ISSUE TITLE
npm run docs

### ISSUE THREAD

**Issue by spiritelf** [airyland/vux#789]
Cannot find resource at /zh-CN/components  如何本地查看文档？

**Comment by airyland** [comment]
``` 
npm run build-docs
npm docs
```

**Comment by spiritelf** [comment]
{ Error: ENOENT: no such file or directory, open 'F:\webpack\vux-sample\vux-2\vu
x-2\docs\zh-CN\demos\x-switch.md'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at infos.forEach.e (F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:47
7:10)
    at Array.forEach (native)
    at buildDemos (F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:441:9)
    at render (F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:215:3)
    at F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:120:3
    at f (F:\webpack\vux-sample\vux-2\vux-2\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (F:\webpack\vux-sample\vux-2\vux-2\node_modules\glob\glo
b.js:151:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'F:\\webpack\\vux-sample\\vux-2\\vux-2\\docs\\zh-CN\\demos\\x-switch.md'
 }
{ Error: ENOENT: no such file or directory, open 'F:\webpack\vux-sample\vux-2\vu
x-2\docs\zh-CN\demos\x-textarea.md'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at infos.forEach.e (F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:47
7:10)
    at Array.forEach (native)
    at buildDemos (F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:441:9)
    at render (F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:215:3)
    at F:\webpack\vux-sample\vux-2\vux-2\build\build-docs.js:120:3
    at f (F:\webpack\vux-sample\vux-2\vux-2\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (F:\webpack\vux-sample\vux-2\vux-2\node_modules\glob\glo
b.js:151:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'F:\\webpack\\vux-sample\\vux-2\\vux-2\\docs\\zh-CN\\demos\\x-textarea.m
d' }

下载最新build 报错
