### ISSUE TITLE
build-components 报错

### ISSUE THREAD

**Issue by huangzhenxian** [airyland/vux#821]
版本："version": "2.1.0-rc.15",

执行 build-components的时候  
![image](https://cloud.githubusercontent.com/assets/8416974/22183047/59a2b3a6-e0ef-11e6-8a68-9cb5fc3f169d.png)

**Comment by huangzhenxian** [comment]
我发现是  build-components.js 里面的 touch.sync(path.resolve(config.output.path, './index.min.css'))
这个是不是处理一些依赖的  例如（Xian zai）我现在要用umd的Swiper 按组件引入只有 Swiper 没有 SwiperItem 然后 SwiperItem 不知道要怎么弄了  我现在只能用vux.min.js引入来弄  但是 400k 有点(fei chang)蛋疼

**Comment by Sapphire2k** [comment]
`/Users/KWAN/Documents/vux/build/build-components.js:60
    var size = assets.size / 1024
                     ^

TypeError: Cannot read property 'size' of undefined
    at /Users/KWAN/Documents/vux/build/build-components.js:60:22
    at Compiler.<anonymous> (/Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/KWAN/Documents/vux/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:267:14)
    at /Users/KWAN/Documents/vux/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/KWAN/Documents/vux/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/KWAN/Documents/vux/node_modules/async/lib/async.js:209:22)
    at Compiler.emitFiles (/Users/KWAN/Documents/vux/node_modules/webpack/lib/Compiler.js:235:20)
    at /Users/KWAN/Documents/vux/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "build-components"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vux@2.1.0-rc.15 build-components: `node build/build-components.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vux@2.1.0-rc.15 build-components script 'node build/build-components.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build-components.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/KWAN/Documents/vux/npm-debug.log
`
我倒是报了一个这样的错，是不是babel没配哇～
