### ISSUE TITLE
vux-loader 出错 没有找到map. json

### ISSUE THREAD

**Issue by zkeyword** [airyland/vux#826]
module.js:472
    throw err;
    ^

Error: Cannot find module 'E:\git\vue2-demo\node_modules\vux\src\components\map.
json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.module.exports.merge (E:\git\vue2-demo\node_modules\vux-loader\s
rc\index.js:186:18)
    at Object.<anonymous> (E:\git\vue2-demo\build\webpack.base.conf.js:106:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by airyland** [comment]
无法确定问题。检查报错位置是否有map.json。

**Comment by zkeyword** [comment]
安装vux-loader没有出现这个文件  我是做其它的版本上找到这个文件  这个版本应该少了这个

**Comment by zkeyword** [comment]
今天刚装的  应该是你刚发的包

**Comment by airyland** [comment]
没有想到原因，你可以去掉大部分代码打个包发我邮箱。

**Comment by airyland** [comment]
确定你装的vux是最新版本的。
